name: Run Tests (in Git)
on: [push]
concurrency: basic-itest
jobs:
  Run-CoreNLP-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup
        run: |
          pwd
          ant clean compile
          echo $CLASSPATH
      - name: Run Basic Tests
        if: always()
        run: |
          ant test
      - run: echo "All tests finished!"
